# Generated by Django 3.0 on 2021-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Session key'),
        ),
    ]
