# Generated by Django 3.0 on 2021-11-02 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20211102_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='session_key',
        ),
        migrations.AddField(
            model_name='vote',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
