# Generated by Django 3.0 on 2021-11-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211102_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Rating'},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='rating',
        ),
    ]
